### ISSUE TITLE
Auto linking with proxy container combined with proxy configuration

### ISSUE THREAD

**Issue by yael-lorenzo** [athena-oss/plugin-php#17]
Why does the Auto linking with proxy container takes place, if I have a configuration file with a different proxy??

It is hard to say if this is a bug or misusage.

The question is why would I use a different proxy from the linking?

**Comment by pproenca** [comment]
Hi @yael-lorenzo-olx 

You can skip the proxy auto link by providing `--skip-proxy`

The auto linking that takes place simply makes a hostname available inside the container, it should not affect anything else, even if you want to use a different proxy hosted in some external host.

In case you have your own implementation of a proxy and you want to use it, you can also provide the option `--link-proxy=<my container name>` to have the athena code link with that container, instead of the one we provide in `plugin-proxy`.

The reason why you would have your own implementation of a proxy server–I don't know–but that option is available for you; it makes the project flexible in case you want to do your own docker magic.

**Comment by pproenca** [comment]
Hey @yael-lorenzo-olx does this issue still make sense ?

**Comment by yael-lorenzo** [comment]
Hello Pedro! Thanks for the previous replay, I don-t remember reading it. It is a good explanation.
